// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdptnrqmyasgwtzehdxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcHRucnFteWFzZ3d0emVoZHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMDk3MzUsImV4cCI6MjA1MTc4NTczNX0.tJvpFjjaubQGxmw9jGXc7f02rnALPep2DewoCD8Gt8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);